# -*- coding: utf-8 -*-
"""student-marks-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWUwUYEMhP48l0G2g5aszwgnDjCSQSuJ
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import matplotlib.pyplot as plt
from sklearn import*
import warnings

"""# Reading data and Visualization"""

df=pd.read_csv('/kaggle/input/students-performance-in-exams/StudentsPerformance.csv')
df

"""# Pre-processing

checking shape of the dataframe and finding leakages
"""

print('shape of the dataframe is : ',df.shape)

for col in df.columns:
    print(col)
    print('number of leakages  :  ',len(df[df[col]==np.NaN]))

"""Data is very good as it does not contain any leakages. As per the data is small if we faced leakages then predicting or making EDA would be tough.

As we don't have to preprocess any leakages we initiate numeration of categorical data

We have to numerate --
1. Gender
2. Race/ethnicity
3. Parental level of Education
4. Lunch
5. Test preparation course

1. gender:   ( 0 - male )     ( 1 - female )
2. lunch:     ( 0 - free/reduced )   ( 1 - standard )
3. test preparation course:     ( 0 - completed )   ( 1 - none )
"""

df['gender'].replace('male',0,inplace=True)
df['gender'].replace('female',1,inplace=True)
df['lunch'].replace('free/reduced',0,inplace=True)
df['lunch'].replace('standard',1,inplace=True)
df['test preparation course'].replace('completed',0,inplace=True)
df['test preparation course'].replace('none',1,inplace=True)
df

"""* Race Numeration"""

for i in range(65,91):
    st='group '
    st+=chr(i)
    print(len(df[df['race/ethnicity']==st]))

"""There are 5 different races.changing them into numeric values

1. group A - 0
2. group B - 1
3. group C - 2
4. group D - 3
5. group E - 4
"""

groups=[]
for i in range(65,70):
    st='group '
    st+=chr(i)
    groups.append(st)
    df['race/ethnicity'].replace(st,i-65,inplace=True)
df

"""* Parental education numeration

1. high school - 0
2. some high school - 0
3. some college - 1
4. bachelor's degree - 2
5. master's degree - 3
6. associate's degree - 4
"""

df['parental level of education'].replace('high school',0,inplace=True)
df['parental level of education'].replace('some high school',0,inplace=True)
df['parental level of education'].replace('some college',1,inplace=True)
df['parental level of education'].replace("associate's degree",2,inplace=True)
df['parental level of education'].replace("master's degree",4,inplace=True)
df['parental level of education'].replace("bachelor's degree",3,inplace=True)
df

"""Total data has been numerated now.
We can perform EDA now.

# EDA : EXPLORATORY DATA ANALYSIS

* gender
"""

sub=['math','reading','writing']

print('no. of girl students : ',len(df[df['gender']==1]))
print('no. of boy students : ',len(df[df['gender']==0]))

"""marks per subject :

"""

boy=[]
girl=[]
mrk=df[df['gender']==0]
boy.append(np.mean(mrk['math score']))
boy.append(np.mean(mrk['reading score']))
boy.append(np.mean(mrk['writing score']))
mrk=df[df['gender']==1]
girl.append(np.mean(mrk['math score']))
girl.append(np.mean(mrk['reading score']))
girl.append(np.mean(mrk['writing score']))
print(boy)
print(girl)
plt.title(' average score per subject')
plt.ylabel('avreage score')
plt.xlabel('subjects')
plt.plot(sub,boy,label='boy')
plt.legend()
plt.plot(sub,girl,label='girl')
plt.legend()
plt.show()

"""Data shows boys have good computational skill whereas girls possess well social interaction skills.

It has also proven by many scientists biologically.

* **race/ethnicity**

Math's Score
"""

math=[]
for i in range(5):
    data=df[df['race/ethnicity']==i]
    tot_sum=sum(data['math score'])
    st='group '
    st+=chr(i+65)
    print(st ,' :   ',tot_sum/len(data))
    math.append(tot_sum/len(data))

"""Reading's score"""

reading=[]
for i in range(5):
    data=df[df['race/ethnicity']==i]
    tot_sum=sum(data['reading score'])
    st='group '
    st+=chr(i+65)
    print(st ,' :   ',tot_sum/len(data))
    reading.append(tot_sum/len(data))

"""Writing score"""

writing=[]
for i in range(5):
    data=df[df['race/ethnicity']==i]
    tot_sum=sum(data['writing score'])
    st='group '
    st+=chr(i+65)
    print(st ,' :   ',tot_sum/len(data))
    writing.append(tot_sum/len(data))

"""Total score"""

tot_score=[]
for i in range(5):
    print(groups[i],'   :    ',(math[i]+reading[i]+writing[i])/3)
    tot_score.append((math[i]+reading[i]+writing[i])/3)

"""Score comparison between racses"""

race=['group A','group B','group C','group D','group E']
plt.plot(race,math,label='math')
plt.legend()
plt.plot(race,reading,label='reading')
plt.legend()
plt.plot(race,writing,label='writing')
plt.legend()
plt.plot(race,tot_score,label='total')
plt.legend()
plt.title('avg score vs race')
plt.xlabel('group')
plt.ylabel('average score')
plt.show()

"""max and min score per race   and range lookup"""

avgg=[]
for i in range(5):
    data=df[df['race/ethnicity']==i]
    pie_data=[]

    print('maximum score in maths',groups[i],'is :  ',max(data['math score']))
    print('minimum score in maths',groups[i],'is :  ',min(data['math score']))

    print('range  :   ',max(data['math score'])-min(data['math score']))
    pie_data.append(max(data['math score'])-min(data['math score']))

    print('maximum score in reading',groups[i],'is :  ',max(data['reading score']))
    print('minimum score in reading',groups[i],'is :  ',min(data['reading score']))

    print('range  :   ',max(data['reading score'])-min(data['reading score']))
    pie_data.append(max(data['reading score'])-min(data['reading score']))

    print('maximum score in writing',groups[i],'is :  ',max(data['writing score']))
    print('minimum score in writing',groups[i],'is :  ',min(data['writing score']))

    print('range  :   ',max(data['writing score'])-min(data['writing score']))
    pie_data.append(max(data['writing score'])-min(data['writing score']))

    avg=(max(data['math score'])-min(data['math score'])+max(data['reading score'])-min(data['reading score'])+max(data['writing score'])-min(data['writing score']))/3
    print('average range :  ',avg)
    avgg.append(avg)
    plt.title('marks variation')
    plt.bar(sub,pie_data)
    plt.show()
plt.bar(groups,avgg)
plt.xticks(rotation=30)
plt.show()

"""This plot shows us that group A,D,E students marks are not much variant but Group B,C have more vairant per subject

Similarly as per whole the group C has the highest variant marks which indicates a great variety of students where as group D are quite consistent over their marks indicating following a similar fashion than others

* **Parental Education**
"""

ped=["high school","some college","associate's degree","bachelor's degree","master's degree"]

pedd=[]
for i in range(5):
    num=len(df[df['parental level of education']==i])
    print('no. of parents have ',ped[i],'  :   ',num)
    pedd.append(num)
plt.plot(ped,pedd,label=ped,color='aqua')
plt.xlabel('parental education type')
plt.xticks(rotation=300)
plt.ylabel('total count')
plt.title('Parental Education')

"""Data stated that as per the duration of study increases number of people dicreased.

That defines an average society.

marks per subject
"""

col=['r','b','g','y','k']

math=[]
reading=[]
writing=[]
for i in range(5):
    mrk=df[df['parental level of education']==i]
    math.append(np.mean(mrk['math score']))
    reading.append(np.mean(mrk['reading score']))
    writing.append(np.mean(mrk['writing score']))
plt.title('Parental educational level analysis')
plt.xlabel('educational level')
plt.ylabel('avg marks')
plt.plot(ped,math,color='r',label='math')
plt.legend()
plt.plot(ped,reading,color='b',label='reading')
plt.legend()
plt.plot(ped,writing,color='g',label='writing')
plt.legend()
plt.xticks(rotation=300)
plt.show()

"""This chart clearly stated that parental education is linearly dependant over child's marks AKA their nursing .
Parents having good educational background helped their children to grow a studious mindset and thus score higher.

Though the marks are increasing , still we can say getting marks in reading and writing are more easy than in maths.

marks variety in different cases
"""

math=[]
reading=[]
writing=[]
plt.title('number variety')
plt.ylabel('range')
for i in range(5):
    mrk=df[df['parental level of education']==i]
    mar=[]
    mar.append(max(mrk['math score'])-min(mrk['math score']))
    math.append(max(mrk['math score'])-min(mrk['math score']))
    mar.append(max(mrk['reading score'])-min(mrk['reading score']))
    reading.append(max(mrk['reading score'])-min(mrk['reading score']))
    mar.append(max(mrk['writing score'])-min(mrk['writing score']))
    writing.append(max(mrk['writing score'])-min(mrk['writing score']))
    plt.plot(sub,mar,label=ped[i])
    plt.legend()

plt.title('marks variety')
plt.xlabel('educational level')
plt.ylabel('range')
plt.plot(ped,math,label='math')
plt.legend()
plt.plot(ped,reading,label='reading')
plt.legend()
plt.plot(ped,writing,label='writing')
plt.legend()
plt.xticks(rotation=300)
plt.show()

"""These 2 curves show us that parental education affects children's marks heavily.

Less educated parent can't guide their child well and that shows that some brilliant student scores very high and some scores very low creating a larger variance.

similarly well educated parent's child have scores moreover in a narrow bound.

We can stii say one more thing ---

parents having bachelor's degree only high school degree possess different consistencies over subjects whereas others are quite similar...

Consistency :  Master's Degree > College going > Associate's Degree > Bachelor's Degree > High school Degree

* Lunch

Basically lunch can help students to have more focus on studies and thus on marks .Let's check that if it can truly visualized by the data.
"""

print('students get lunch :',len(df[df['lunch']==0]))
print("student doesen't get enough lunch :",len(df[df['lunch']==1]))

"""Average Score"""

lun=['no/less','complete']
math=[]
reading=[]
writing=[]
for i in range(2):
    dat=df[df['lunch']==i]
    math.append(np.mean(dat['math score']))
    reading.append(np.mean(dat['reading score']))
    writing.append(np.mean(dat['writing score']))
plt.title('Lunch vs. Average Score')
plt.plot(lun,math,label='math')
plt.plot(lun,reading,label='reading')
plt.plot(lun,writing,label='writing')
plt.xlabel('lunch condition')
plt.ylabel('average score')
plt.show()

"""Clearly visible that the previous conclusion proved here.

Lunch vs. Parental Education
"""

plt.title('Average score analysis on lunch and parental education(combined) ')
plt.xlabel('subjects')
plt.ylabel('Average score')
for i in range(5):
    dt=df[df['parental level of education']==i]
    for j in range(2):
        dt1=dt[dt['lunch']==j]
        m=np.mean(dt1['math score'])
        r=np.mean(dt1['reading score'])
        w=np.mean(dt1['writing score'])
        arr=[]
        arr.append(m)
        arr.append(r)
        arr.append(w)
        st=str(lun[j]+' -- '+ ped[i])
        plt.plot(sub,arr,label=st)
        plt.legend()

"""This graph showed us that students having standard lunch are scoring more than who had less or no lunch.
This graph also showed us that combining well educated parent's child are scoring more over others.

So,
Conclusion :   
* Score is proportional to *education of parents*.              
* Score is proportional to having *proper lunch*.

* **test preparation course**

Altough family status matters in scoring good marks , still a preparation over the exam may change the scores a lot.
"""

pr=df[df['test preparation course']==0]
print('prepared for exams',len(pr))
pr1=df[df['test preparation course']==1]
print('not prepared for exams',len(pr1))

"""average marks"""

st=[]
nst=[]
st.append(np.mean(pr['math score']))
st.append(np.mean(pr['reading score']))
st.append(np.mean(pr['writing score']))
nst.append(np.mean(pr1['math score']))
nst.append(np.mean(pr1['reading score']))
nst.append(np.mean(pr1['writing score']))
plt.title('Average score per preparation')
plt.xlabel('subjects')
plt.ylabel('average marks')
plt.plot(sub,st,label='had preparation course')
plt.legend()
plt.plot(sub,nst,label="had no preparation courses")
plt.legend()
plt.show()

"""Hence proved that having preparation helped the student to score a lot more than others.

Scores of math are low all over every possibilites. So, it is clear the dataset is made based on students who are weaker in math and good in reading-writing.

Here the EDA ends.

# Please upvote if you like this EDA  :)

You can join my discoed server where I try to analyze over mant datasets:
Discord Link : https://discord.gg/zSK9an6J     (Atlantic Data Studio)
"""